<?php

namespace Feeld\Display\CLI;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-26 at 18:05:25.
 */
class SymfonyConsoleDisplayTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SymfonyConsoleDisplay
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SymfonyConsoleDisplay;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Display\CLI\SymfonyConsoleDisplay::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\CLI\SymfonyConsoleDisplay::informAboutStructure
     * @todo   Implement testInformAboutStructure().
     */
    public function testInformAboutStructure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
