<?php

namespace Feeld\Display;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-22 at 23:07:30.
 */
class HTMLBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HTMLBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Display\HTMLBuilder::setThreshold
     * @todo   Implement testSetThreshold().
     */
    public function testSetThreshold() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTMLBuilder::createHTMLElement
     * @todo   Implement testCreateHTMLElement().
     */
    public function testCreateHTMLElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTMLBuilder::createHTMLElementWithAttributes
     * @todo   Implement testCreateHTMLElementWithAttributes().
     */
    public function testCreateHTMLElementWithAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTMLBuilder::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
