<?php

namespace Feeld\Interview;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-14 at 13:19:48.
 */
class ErrorContainerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ErrorContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ErrorContainer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Interview\ErrorContainer::clear
     */
    public function testClear() {
        $this->assertTrue($this->object->hasPassed());
        $this->object->add(new \Wellid\ValidationResult(false));
        $this->assertFalse($this->object->hasPassed());
        $this->object->clear();
        $this->assertTrue($this->object->hasPassed());
    }

    /**
     * @covers Feeld\Interview\ErrorContainer::getDisplay
     * @todo   Implement testGetDisplay().
     */
    public function testGetDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\ErrorContainer::setDisplay
     * @todo   Implement testSetDisplay().
     */
    public function testSetDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\ErrorContainer::refreshDisplay
     * @todo   Implement testRefreshDisplay().
     */
    public function testRefreshDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\ErrorContainer::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
