<?php

namespace Feeld\Interview;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-14 at 13:19:48.
 */
class HTMLFormInternalFieldsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HTMLFormInternalFields
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLFormInternalFields;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Interview\HTMLFormInternalFields::setUID
     * @covers Feeld\Interview\HTMLFormInternalFields::getUID
     * @todo   Implement testSetUID().
     */
    public function testSetUID() {
        $this->assertNull($this->object->getUID());
        $this->object->setUID('form25');
        $this->assertEquals('form25', $this->object->getUID());
    }

    /**
     * @covers Feeld\Interview\HTMLFormInternalFields::setPageNumber
     */
    public function testSetPageNumber() {
        $this->assertNull($this->object->getPageNumber());
        $this->object->setPageNumber(2);
        $this->assertEquals(2, $this->object->getPageNumber());
    }

}
