<?php

namespace Feeld\Interview;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-06 at 14:03:59.
 */
class HTMLFormTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HTMLForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Interview\HTMLForm::getMethod
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\HTMLForm::inviteAnswers
     * @todo   Implement testInviteAnswers().
     */
    public function testInviteAnswers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\HTMLForm::onValidationError
     * @todo   Implement testOnValidationError().
     */
    public function testOnValidationError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\HTMLForm::onValidationSuccess
     * @todo   Implement testOnValidationSuccess().
     */
    public function testOnValidationSuccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\HTMLForm::retrieveAnswers
     * @todo   Implement testRetrieveAnswers().
     */
    public function testRetrieveAnswers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
