<?php

namespace Feeld\Interview;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-16 at 15:55:43.
 */
class SymfonyConsoleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SymfonyConsole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new SymfonyConsole;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::inviteAnswers
     * @todo   Implement testInviteAnswers().
     */
    public function testInviteAnswers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::onValidationError
     * @todo   Implement testOnValidationError().
     */
    public function testOnValidationError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::onValidationSuccess
     * @todo   Implement testOnValidationSuccess().
     */
    public function testOnValidationSuccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::retrieveAnswers
     * @todo   Implement testRetrieveAnswers().
     */
    public function testRetrieveAnswers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::getCurrentCollection
     * @todo   Implement testGetCurrentCollection().
     */
    public function testGetCurrentCollection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::skipToCollection
     * @todo   Implement testSkipToCollection().
     */
    public function testSkipToCollection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::nextCollection
     * @todo   Implement testNextCollection().
     */
    public function testNextCollection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::getCurrentValidAnswers
     * @todo   Implement testGetCurrentValidAnswers().
     */
    public function testGetCurrentValidAnswers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Interview\SymfonyConsole::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
