<?php

namespace Feeld\FieldCollection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-25 at 13:01:45.
 */
class FieldCollectionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FieldCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FieldCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::getFieldsByClass
     * @todo   Implement testGetFieldsByClass().
     */
    public function testGetFieldsByClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::getFieldsByDataType
     * @todo   Implement testGetFieldsByDataType().
     */
    public function testGetFieldsByDataType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::getMandatoryFields
     * @todo   Implement testGetMandatoryFields().
     */
    public function testGetMandatoryFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::count
     * @covers Feeld\FieldCollection\FieldCollection::current
     * @covers Feeld\FieldCollection\FieldCollection::key
     * @covers Feeld\FieldCollection\FieldCollection::next
     * @covers Feeld\FieldCollection\FieldCollection::key
     * @covers Feeld\FieldCollection\FieldCollection::rewind
     */
    public function testForeach() {
        $this->assertEquals(0, count($this->object));
        $this->object->addField(new \Feeld\Field\Select(new \Feeld\DataType\URL()));
        $this->object->addFields(
            new \Feeld\Field\Select(new \Feeld\DataType\URL()),
            new \Feeld\Field\CloakedEntry(new \Feeld\DataType\Str())
        );
        $this->assertEquals(3, count($this->object));
        
        foreach($this->object as $key => $value) {
            $this->assertInstanceOf('\Feeld\FieldInterface', $value);
            $this->assertInternalType('int', $key);
        }
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::addFields
     * @todo   Implement testAddFields().
     */
    public function testAddFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::addField
     * @todo   Implement testAddField().
     */
    public function testAddField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::getFields
     * @todo   Implement testGetFields().
     */
    public function testGetFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\FieldCollection\FieldCollection::getFieldById
     * @todo   Implement testGetFieldById().
     */
    public function testGetFieldById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
