<?php

namespace Feeld\FieldCollection;

class TestObject {
    private $a = '1';
    protected $b = '2';
    public $c = '3';
    
    public function getABC() {
        return $this->a.$this->b.$this->c;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-14 at 13:19:48.
 */
class ValueMapStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ValueMapStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValueMapStrategy(ValueMapStrategy::MAP_REFLECTION, 'b');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\FieldCollection\ValueMapStrategy::set
     */
    public function testSet() {
        $test = new TestObject();
        
        $this->object->set($test, '7');
        $this->assertEquals('173', $test->getABC());
    }

    /**
     * @covers Feeld\FieldCollection\ValueMapStrategy::getSupportedStrategies
     */
    public function testGetSupportedStrategies() {
        $strategies = ValueMapStrategy::getSupportedStrategies();
        $this->assertNotEmpty($strategies);
        $this->assertContainsOnly('int', $strategies);
    }

}
