<?php

namespace Feeld\Display\HTML;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-14 at 13:19:49.
 */
class ButtonTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Button
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Button;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Display\HTML\Button::informAboutStructure
     * @todo   Implement testInformAboutStructure().
     */
    public function testInformAboutStructure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
