<?php

namespace Feeld\Display\HTML;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-22 at 23:07:31.
 */
class ElementTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Element
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Element('div');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Display\HTML\Element::addCssClass
     * @todo   Implement testAddCssClass().
     */
    public function testAddCssClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTML\Element::isVoid
     * @todo   Implement testIsVoid().
     */
    public function testIsVoid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTML\Element::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTML\Element::setAttribute
     * @todo   Implement testSetAttribute().
     */
    public function testSetAttribute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Display\HTML\Element::setContent
     * @todo   Implement testSetContent().
     */
    public function testSetContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
