<?php

namespace Feeld\Field\DataType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-22 at 23:10:06.
 */
class DateTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Date;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\DataType\Date::setMin
     * @todo   Implement testSetMin().
     */
    public function testSetMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::setMax
     * @todo   Implement testSetMax().
     */
    public function testSetMax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::setStep
     * @todo   Implement testSetStep().
     */
    public function testSetStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getMin
     * @todo   Implement testGetMin().
     */
    public function testGetMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getMax
     * @todo   Implement testGetMax().
     */
    public function testGetMax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getStep
     * @todo   Implement testGetStep().
     */
    public function testGetStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getPrimitiveType
     * @todo   Implement testGetPrimitiveType().
     */
    public function testGetPrimitiveType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getFilteredValue
     * @todo   Implement testGetFilteredValue().
     */
    public function testGetFilteredValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getRawValue
     * @todo   Implement testGetRawValue().
     */
    public function testGetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getSanitizer
     * @todo   Implement testGetSanitizer().
     */
    public function testGetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::clearValidationResult
     * @todo   Implement testClearValidationResult().
     */
    public function testClearValidationResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::setSanitizer
     * @todo   Implement testSetSanitizer().
     */
    public function testSetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::rawValueFromInput
     * @todo   Implement testRawValueFromInput().
     */
    public function testRawValueFromInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Date::setRawValue
     * @todo   Implement testSetRawValue().
     */
    public function testSetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
