<?php

namespace Feeld\Field\DataType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-22 at 23:10:06.
 */
class FileTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new File;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\DataType\File::setAccept
     * @todo   Implement testSetAccept().
     */
    public function testSetAccept() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\File::getAccept
     * @todo   Implement testGetAccept().
     */
    public function testGetAccept() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\File::setMaxFilesize
     * @todo   Implement testSetMaxFilesize().
     */
    public function testSetMaxFilesize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\File::getMaxFilesize
     * @todo   Implement testGetMaxFilesize().
     */
    public function testGetMaxFilesize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\File::setMaxFilesizeKilobytes
     * @todo   Implement testSetMaxFilesizeKilobytes().
     */
    public function testSetMaxFilesizeKilobytes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\File::setMaxFilesizeMegabytes
     * @todo   Implement testSetMaxFilesizeMegabytes().
     */
    public function testSetMaxFilesizeMegabytes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
