<?php

namespace Feeld\Field\DataType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-22 at 23:10:05.
 */
class FloatTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Float
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Float;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\DataType\Float::getPrimitiveType
     * @todo   Implement testGetPrimitiveType().
     */
    public function testGetPrimitiveType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getFilteredValue
     * @todo   Implement testGetFilteredValue().
     */
    public function testGetFilteredValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getRawValue
     * @todo   Implement testGetRawValue().
     */
    public function testGetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getSanitizer
     * @todo   Implement testGetSanitizer().
     */
    public function testGetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::clearValidationResult
     * @todo   Implement testClearValidationResult().
     */
    public function testClearValidationResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setMinLength
     * @todo   Implement testSetMinLength().
     */
    public function testSetMinLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setMaxLength
     * @todo   Implement testSetMaxLength().
     */
    public function testSetMaxLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getMinLength
     * @todo   Implement testGetMinLength().
     */
    public function testGetMinLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getMaxLength
     * @todo   Implement testGetMaxLength().
     */
    public function testGetMaxLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::hasMinLength
     * @todo   Implement testHasMinLength().
     */
    public function testHasMinLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::hasMaxLength
     * @todo   Implement testHasMaxLength().
     */
    public function testHasMaxLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setMin
     * @todo   Implement testSetMin().
     */
    public function testSetMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setMax
     * @todo   Implement testSetMax().
     */
    public function testSetMax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getMin
     * @todo   Implement testGetMin().
     */
    public function testGetMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getMax
     * @todo   Implement testGetMax().
     */
    public function testGetMax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::getStep
     * @todo   Implement testGetStep().
     */
    public function testGetStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setStep
     * @todo   Implement testSetStep().
     */
    public function testSetStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::hasStep
     * @todo   Implement testHasStep().
     */
    public function testHasStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::hasMin
     * @todo   Implement testHasMin().
     */
    public function testHasMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::hasMax
     * @todo   Implement testHasMax().
     */
    public function testHasMax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setSanitizer
     * @todo   Implement testSetSanitizer().
     */
    public function testSetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::rawValueFromInput
     * @todo   Implement testRawValueFromInput().
     */
    public function testRawValueFromInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\DataType\Float::setRawValue
     * @todo   Implement testSetRawValue().
     */
    public function testSetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
