<?php

namespace Feeld\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-22 at 23:10:06.
 */
class CheckboxTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Checkbox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Checkbox;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\Checkbox::rawValueFromInput
     * @todo   Implement testRawValueFromInput().
     */
    public function testRawValueFromInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::setRawValue
     * @todo   Implement testSetRawValue().
     */
    public function testSetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getFilteredValue
     * @todo   Implement testGetFilteredValue().
     */
    public function testGetFilteredValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getRawValue
     * @todo   Implement testGetRawValue().
     */
    public function testGetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getSanitizer
     * @todo   Implement testGetSanitizer().
     */
    public function testGetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::clearValidationResult
     * @todo   Implement testClearValidationResult().
     */
    public function testClearValidationResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getDefault
     * @todo   Implement testGetDefault().
     */
    public function testGetDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::setDefault
     * @todo   Implement testSetDefault().
     */
    public function testSetDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::hasDefault
     * @todo   Implement testHasDefault().
     */
    public function testHasDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::hasId
     * @todo   Implement testHasId().
     */
    public function testHasId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::setRequired
     * @todo   Implement testSetRequired().
     */
    public function testSetRequired() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::isRequired
     * @todo   Implement testIsRequired().
     */
    public function testIsRequired() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getOptions
     * @todo   Implement testGetOptions().
     */
    public function testGetOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::addOption
     * @todo   Implement testAddOption().
     */
    public function testAddOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::addOptions
     * @todo   Implement testAddOptions().
     */
    public function testAddOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::setSanitizer
     * @todo   Implement testSetSanitizer().
     */
    public function testSetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\Field\Checkbox::getDataType
     * @todo   Implement testGetDataType().
     */
    public function testGetDataType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
