<?php

namespace Feeld\Field\SymfonyConsole;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-16 at 14:38:11.
 */
class SymfonyConsoleCheckboxTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SymfonyConsoleCheckbox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SymfonyConsoleCheckbox;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\SymfonyConsole\SymfonyConsoleCheckbox::refreshDisplay
     * @todo   Implement testRefreshDisplay().
     */
    public function testRefreshDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
