<?php

namespace Feeld\Field\SymfonyConsole;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-26 at 17:44:48.
 */
class SymfonyConsoleEntryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SymfonyConsoleEntry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SymfonyConsoleEntry(new \Feeld\DataType\Str(), 'your name', new \Feeld\Display\CLI\SymfonyConsoleDisplay());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\SymfonyConsole\SymfonyConsoleEntry::refreshDisplay
     * @todo   Implement testRefreshDisplay().
     */
    public function testRefreshDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
