<?php

namespace Feeld\Field\SymfonyConsole;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-16 at 14:53:55.
 */
class SymfonyConsoleSelectTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SymfonyConsoleSelect
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SymfonyConsoleSelect(new \Feeld\DataType\URL(), 'your url', new \Feeld\Display\CLI\SymfonyConsoleDisplay());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\Field\SymfonyConsole\SymfonyConsoleSelect::refreshDisplay
     * @todo   Implement testRefreshDisplay().
     */
    public function testRefreshDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
