<?php

namespace Feeld\DataType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-16 at 14:03:21.
 */
class BooleanTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Boolean
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Boolean;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Feeld\DataType\Boolean::transformSanitizedValue
     * @todo   Implement testTransformSanitizedValue().
     */
    public function testTransformSanitizedValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\DataType\Boolean::getSanitizer
     * @covers Feeld\DataType\Boolean::setSanitizer
     */
    public function testGetSanitizer() {
        $this->assertInstanceOf(get_class(new \Sanitor\Sanitizer(FILTER_DEFAULT)), $this->object->getSanitizer());
        $this->assertNotEquals(FILTER_SANITIZE_URL, $this->object->getSanitizer()->getSanitizeFilter());
        $this->object->setSanitizer(new \Sanitor\Sanitizer(FILTER_SANITIZE_URL));
        $this->assertEquals(FILTER_SANITIZE_URL, $this->object->getSanitizer()->getSanitizeFilter());
    }

    /**
     * @covers Feeld\DataType\Boolean::getLastSanitizedValue
     * @todo   Implement testGetLastSanitizedValue().
     */
    public function testGetLastSanitizedValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\DataType\Boolean::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\DataType\Boolean::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\DataType\Boolean::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Feeld\DataType\Boolean::validateValue
     * @todo   Implement testValidateValue().
     */
    public function testValidateValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
